name: Merge original repo once a day at midnight (UTC)
on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 10 * * *"
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: merge
        run: | 
              pwd
              cd /home/runner/work/jenkins/jenkins
              git fetch upstream
              git merge upstream/master
