name: Merge original repo once a day at midnight (UTC)
on:
  push:
    branches:
      - master
  schedule:
    - cron: "30 10 * * *"
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: fetch upstream
        run: git fetch upstream
      - name: merge
        run: git merge upstream/master
