name: Merge original repo once a day at midnight
on:
  schedule:
    - cron: "22 8 * * *"
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - name: fetch upstream
        run: git fetch upstream
      - name: merge
        run: git merge upstream/master
